!SET variable_substitution=true;
USE ROLE &{PROGRAM}_&{ENV}_DATA_LOADER;
USE WAREHOUSE &{PROGRAM}_&{ENV}_LOADING_WH;
USE DATABASE &{PROGRAM}_&{ENV}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE TABLE IF NOT EXISTS AIRFLOW_ETL_CONTROL_TBL (
    DAG_NAME VARCHAR NOT NULL
    , DAG_RUN VARCHAR NOT NULL
    , DAG_RUN_STATE VARCHAR NOT NULL
    , DAG_RUN_START_DATE VARCHAR NOT NULL
    , DAG_RUN_END_DATE TIMESTAMP_NTZ NOT NULL
    , DAG_RUN_DURATION VARCHAR NOT NULL
    , DAG_RUN_TASK_NAME VARCHAR NOT NULL
    , DAG_RUN_TASK_STATE VARCHAR NOT NULL
    , DAG_RUN_TASK_START_DATE TIMESTAMP_NTZ NOT NULL
    , DAG_RUN_TASK_END_DATE TIMESTAMP_NTZ NOT NULL
    , DAG_RUN_TASK_DURATION VARCHAR NOT NULL
    , QUERY_TS TIMESTAMP_NTZ NOT NULL
    --last_run?
    --next_run?
);

CREATE TABLE IF NOT EXISTS AIRFLOW_DAG (
    DAG_NAME VARCHAR NOT NULL
    , DAG_SCHEDULE VARCHAR NOT NULL
    , TARGET_TBL VARCHAR
    --last_run?
    --next_run?
);
