!SET variable_substitution=true;
USE ROLE &{PROGRAM}_&{ENV}_DATA_LOADER;
USE WAREHOUSE &{PROGRAM}_&{ENV}_LOADING_WH;
USE DATABASE &{PROGRAM}_&{ENV}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE TABLE IF NOT EXISTS AIRFLOW_DAG (
    DAG_NAME VARCHAR NOT NULL
    , DAG_SCHEDULE VARCHAR NOT NULL
    , TARGET_TBL VARCHAR
    --last_run?
    --next_run?
);
