!SET variable_substitution=true;
--define the role hierarchy
USE ROLE SECURITYADMIN;
GRANT ROLE &{PROGRAM}_&{ENV}_DBA TO ROLE SYSADMIN;
GRANT ROLE &{PROGRAM}_&{ENV}_DBT_SVC TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_DEVELOPER TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_ANALYST TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_VISUALISER TO ROLE &{PROGRAM}_&{ENV}_ANALYST;

--grant &{PROGRAM}_&{ENV}_SF_TASK_ADMIN, &{PROGRAM}_&{ENV}_SF_STAGE_ADMIN role to &{PROGRAM}_&{ENV}_DBA
GRANT ROLE &{PROGRAM}_&{ENV}_SF_TASK_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_SF_STAGE_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_SF_STAGE_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DATA_LOADER;
GRANT ROLE &{PROGRAM}_&{ENV}_SF_SI_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;
