!SET variable_substitution=true;
USE ROLE SECURITYADMIN;
GRANT ROLE &{PROGRAM}_&{ENV}_DBA TO USER [EXAMPLE_USER];
GRANT ROLE &{PROGRAM}_&{ENV}_DBT_SVC TO USER [EXAMPLE_USER];
--GRANT ROLE ACCOUNTADMIN TO USER &{PROGRAM}_&{ENV}_SNOWFLAKE_PIPELINE_DEPLOYMENT_USER;
